### ISSUE TITLE
Runtime error on trained model

### ISSUE THREAD

**Issue by ufukefe** [RanhaoKang/PWC-Net_pytorch#16]
Hi again, I have trained SintelClean dataset for 1500/200000 and got the model. But when I try to test it, a Runtime error occurs. "RuntimeError: Error(s) in loading state_dict for Net:
	Missing key(s) in state_dict: "feature_pyramid_extractor.Feature(Lv0).0.1.weight"....... and goes like this. I think it is abour pytorch version but I am using Pytorch version 0.4.0 as you did and I can test it with your model properly. But I have this problem with my model. Do you have any suggestion? Thanks

**Comment by SlinkoIgor** [comment]
had similar error. It was caused by my mistake: I removed  --input_norm --batch_norm from args due to parsing error. But should change them by  --input-norm --batch-norm (notice - instead of _)
