### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by mathmanu** [RanhaoKang/PWC-Net_pytorch#7]
Thank you for this work. Looking forward to your results and benchmarking.

Could you please add a LICENSE file? That will help me to cleanly cite your work if I use your code.
If possible an MIT license like this: 
https://github.com/ClementPinard/FlowNetPytorch/blob/master/LICENSE
Or a BSD license like this one:
https://github.com/pytorch/vision/blob/master/LICENSE

Also if you copied the correlation layer or any other code from somewhere else, it should be clearly mentioned.

**Comment by RanhaoKang** [comment]
Thanks for reminding me. an MIT license is added.
